export const COUNTRIES = {
  RU: 'Russia',
  DK: 'Denmark',
  NL: 'Netherlands',
  NO: 'Norway',
  ES: 'Spain',
  IT: 'Italy',
  GR: 'Greece',
  GB: 'United Kingdom',
  IE: 'Ireland',
  TH: 'Thailand',
  PL: 'Polska',
  US: 'United States',
  IS: 'Iceland',
  DE: 'Germany',
  KZ: 'Kazakhstan',
  FR: 'France',
  MX: 'Mexico',
  BE: 'Belgium',
  SE: 'Sweden',
  CL: 'Chile',
  CY: 'Cyprus',
  BR: 'Brazil',
  AU: 'Australia',
  CA: 'Canada',
  UK: 'Ukraine',
  AR: 'Argentina',
  PT: 'Portugal',
  LU: 'Luxembourg',
  SI: 'Slovenia',
  LT: 'Lithuania',
  JP: 'Japan',
  AE: 'United Arab Emirates',
  RO: 'Romania',
  TR: 'Turkey',
  AT: 'Austria',
  FI: 'Finland',
  IL: 'Israel',
  SK: 'Slovakia',
  CO: 'Colombia',
  GE: 'Georgia',
  CH: 'Switzerland',
  ME: 'Montenegro',
  NZ: 'New Zealand',
  LV: 'Latvia',
  BG: 'Bulgaria',
  HR: 'Croatia',
  SA: 'Saudi Arabia',
  UA: 'Ukraine',
  MT: 'Malta',
  BA: 'Bosnia and Herzegovina',
  AW: 'Aruba',
  IN: 'India',
  EE: 'Estonia',
  LB: 'Lebanon',
  KW: 'Kuwait',
  HU: 'Hungary',
};
